apiVersion: v1
kind: Namespace
metadata:
  name: gosdk
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gosdk
  name: goapp
---
apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  namespace: minio-tenant-1
spec:
  application:
    namespace: gosdk
    serviceaccount: goapp
  policies:
    - kafka-rw
---
apiVersion: batch/v1
kind: Job
metadata:
  name: go-example
  namespace: gosdk
spec:
  serviceAccountName: goapp
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: go-sdk
          image: pjuarezd/minio-operator-sts-example-go
          env:
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
